# Generated by Django 4.2.2 on 2023-07-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products '},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'ProductCategory', 'verbose_name_plural': 'Categories '},
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
