# Generated by Django 4.2.3 on 2023-07-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_stripe_product_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='striple_product_price_id',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
    ]
