# Generated by Django 4.2.3 on 2023-07-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_striple_product_price_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='striple_product_price_id',
            new_name='stripe_product_price_id',
        ),
    ]
