# Generated by Django 4.2.3 on 2023-09-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_basket_product_en_basket_product_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product_en',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='product_ru',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='product_uz',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='quantity_en',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='quantity_ru',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='quantity_uz',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='name_uz',
        ),
    ]
